// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearPresence():Promise<void>;

export function GetSongs():Promise<Array<main.Song>>;

export function UpdatePresence(arg1:string,arg2:string):Promise<void>;
