// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearPresence() {
  return window['go']['main']['App']['ClearPresence']();
}

export function GetSongs() {
  return window['go']['main']['App']['GetSongs']();
}

export function UpdatePresence(arg1, arg2) {
  return window['go']['main']['App']['UpdatePresence'](arg1, arg2);
}
